init:
	@echo "terraform initialise..."
	terraform init
	@echo "terraform formatting.."
	terraform fmt

validate:
	@echo "terraform validate..."
	terraform validate

apply:
	@echo "terraform apply..."
	terraform apply

show:
	@echo "terraform show..."
	terraform show	
